[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''    
    set t_Co=256
    colorscheme jellybeans
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
    let g:template_basedir = '~/.vim'
    let g:template_free_pattern = 'template'
    au MyAutoCmd User plugin-template-loaded call s:template_keywords()
    function! s:template_keywords()
        silent! %s/<+DATE+>/\=strftime('%Y-%m-%d')/g
        silent! %s/<+FILENAME+>/\=expand('%:r')/g
    endfunction
    autocmd MyAutoCmd User plugin-template-loaded
        \   if search('<+CURSOR+>')
        \ |   silent! execute 'normal! "_da>'
        \ | endif
'''

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo =  'thinca/vim-quickrun'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'mattn/vim-starwars'

[[plugins]]
repo = 'skanehira/badapple.vim'

