[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['javascript', 'rust']
hook_add = '''
    let g:syntastic_enable_signs = 1
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 0
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 1

    let g:syntastic_javascript_checkers = ['jshint']
    let g:syntastic_rust_checkers = ['rustc', 'cargo']
    let g:syntastic_python_checkers = ['flake8']
    let g:syntastic_mode_map = { 'mode': 'active',
        \ 'active_filetypes': ['javascript', 'rust', 'python'],
        \ 'passive_filetypes': [] }
'''

[[plugins]]
repo  = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
hook_add = '''
    let g:racer_cmd = '__HOMEPATH__/.cargo/bin/racer'
    let $RUST_SRC_PATH='__HOMEPATH__/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src'
'''

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']
